# Generated by Django 2.2 on 2022-03-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('cover_image', models.FileField(upload_to='')),
                ('highest_sale', models.CharField(default='0', max_length=50)),
                ('floor_price', models.CharField(default='0', max_length=50)),
                ('marketcap', models.CharField(default='0', max_length=50)),
                ('items', models.CharField(default='0', max_length=50)),
                ('owners', models.CharField(default='0', max_length=50)),
                ('total_volume', models.CharField(default='0', max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='index.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=2000)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=50)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pay_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=50)),
                ('wallet', models.CharField(default='0', max_length=500)),
                ('image', models.FileField(upload_to='')),
                ('visible', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='0', max_length=50)),
                ('name', models.CharField(default='0', max_length=50)),
                ('price', models.CharField(default='0', max_length=50)),
                ('wallet', models.CharField(default='0', max_length=500)),
                ('image', models.FileField(upload_to='')),
                ('approve', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Price_logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=50)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=50)),
                ('price', models.CharField(default='0', max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('slug', models.SlugField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft', to='index.Category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='index.Nft')),
                ('price_logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Price_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=50)),
                ('price', models.CharField(default='0', max_length=50)),
                ('qutity', models.CharField(default='0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Nft')),
            ],
        ),
    ]
